### ISSUE TITLE
[Feature Request] Add `legacy` tag/label to legacy entry creatures

### ISSUE THREAD

**Issue by Setnour6** [5etools-mirror-1/5etools-mirror-1.github.io#126] opened 2023-12-08 04:29 UTC
### Is this a bug or a feature request 

Feature Request

### Are you willing to contribute to the feature

No, due to IRL commitments

### Page(s) affected:

The entire bestiary

### Additional information

The feature allows for the `legacy` tag/label to be added to the creatures in the bestiary that are marked as `legacy` in the original source. You can also add a `legacy` filter or toggle to show or hide creatures with the legacy tag/label.

Concepts (created using paint.net):
![image](https://github.com/5etools-mirror-1/5etools-mirror-1.github.io/assets/70764728/50c28823-4ec0-44a6-9c60-95150c685116)
![image](https://github.com/5etools-mirror-1/5etools-mirror-1.github.io/assets/70764728/9e671be4-4a06-4b94-8cf2-6f9c901044aa)
![image](https://github.com/5etools-mirror-1/5etools-mirror-1.github.io/assets/70764728/9a06484e-e8a7-4543-8014-154f360530ae)

Of course, the tag/label background will be lighter than what is displayed, or to at least make the text appear better in contrast.

### Browser (Chromium, Firefox, Edge, etc):

Edge

### Platform (Windows, iOS, Android, etc):

Windows, but I use iOS too.

**Comment by revilowaldow** [comment] 2023-12-08 05:02
5ET-928

**Comment by Setnour6** [comment] 2023-12-08 13:11
> 5ET-928

I have no idea what that means

**Comment by revilowaldow** [comment] 2023-12-08 21:40
Suggestions and feature requests are generally tracked through the [community discord](https://discord.gg/5etools)

In this case your suggestion is a duplicate of existing suggestion 5ET-928. Please visit the discord to vote for it.

You can see the status of it here https://github.com/5etools/tracker/issues/1110 but please interact with it in Discord and not on the GitHub issue.

**Comment by Setnour6** [comment] 2023-12-08 22:46
> Suggestions and feature requests are generally tracked through the [community discord](https://discord.gg/5etools)
> 
> In this case your suggestion is a duplicate of existing suggestion 5ET-928. Please visit the discord to vote for it.
> 
> You can see the status of it here [5etools/tracker#1110](https://github.com/5etools/tracker/issues/1110) but please interact with it in Discord and not on the GitHub issue.

I didn't want to use discord but okay

**Comment by TheGiddyLimit** [comment] 2023-12-10 22:16
(switched to tracking in Discord)

**Closed by TheGiddyLimit** 2023-12-10 22:16 UTC
